import randomString from "randomstring";

import { randomGeneratorParameter } from "../../config";

/**
 * @description => this function will generate unique id & return it
 */
export const uidGenerator = () => randomString.generate(randomGeneratorParameter);

/**
 * @description => code will generate a unique users id with first character 
 * users firstname & second character will be lastname first character
 * 
 * @param {Object} userObj 
 */
export const inviteFriendUidGenerator = ()=> `IND_JAIN__${uidGenerator()}`;

/**
 * @description => generate unqiue code for the FILE with  
 * FILE_ then unqiue id generated by randomstring
 */
export const fileUidGenerator = ()=>`FILE_${uidGenerator()}`;

/**
 * @description => generate unqiue code for the cookie with  
 * COOKIE_ then unqiue id generated by randomstring
 */
export const cookieUidGenerator = ()=> `COOKIE_${uidGenerator()}`;

